parameters:
    nerdery_csv.factory.file_reader.class: Nerdery\CsvBundle\FileReader\Factory\CsvFileReaderFactory

services:
    nerdery_csv.factory.file_reader:
        class: %nerdery_csv.factory.file_reader.class%
        arguments: []
