parameters:
    nerdery_csv.factory.file_reader.class: Nerdery\CsvBundle\FileReader\Factory\CsvFileReaderFactory
    nerdery_csv.error_reporter.class: Nerdery\CsvBundle\Error\Reporter
    nerdery_csv.subscriber.parse_error.class: Nerdery\CsvBundle\Subscriber\ParseErrorSubscriber
services:
    nerdery_csv.factory.file_reader:
        class: %nerdery_csv.factory.file_reader.class%
        arguments:
            - @event_dispatcher

    nerdery_csv.error_reporter:
        class: %nerdery_csv.error_reporter.class%
        arguments:

    nerdery_csv.subscriber.parse_error:
        class: %nerdery_csv.subscriber.parse_error.class%
        arguments:
            - @nerdery_csv.error_reporter
        tags:
            - { name: kernel.event_subscriber }
